/**
 * generate-approved-phrases.ts — Generate approved phrase packs for all supported languages
 *
 * Usage: npx ts-node scripts/generate-approved-phrases.ts
 *
 * This script outputs the approved phrase pack as JSON for review before import.
 * Emergency and wayfinding phrases are pre-approved and NOT generated by AI.
 */

interface ApprovedPhraseEntry {
  phraseKey: string;
  category: 'emergency' | 'wayfinding' | 'hospitality' | 'transport';
  icon: string;
  translations: Record<string, string>;
}

const phrases: ApprovedPhraseEntry[] = [
  // Emergency
  { phraseKey: 'need_hospital', category: 'emergency', icon: '🏥', translations: { en: 'I need a hospital', es: 'Necesito un hospital', fr: "J'ai besoin d'un hôpital", ar: 'أحتاج إلى مستشفى', pt: 'Preciso de um hospital', ja: '病院が必要です', ko: '병원이 필요합니다', 'zh-CN': '我需要去医院', de: 'Ich brauche ein Krankenhaus', it: 'Ho bisogno di un ospedale' } },
  { phraseKey: 'need_police', category: 'emergency', icon: '🚔', translations: { en: 'I need police', es: 'Necesito policía', fr: "J'ai besoin de la police", ar: 'أحتاج الشرطة', pt: 'Preciso de polícia', ja: '警察が必要です', ko: '경찰이 필요합니다', 'zh-CN': '我需要警察', de: 'Ich brauche die Polizei', it: 'Ho bisogno della polizia' } },
  { phraseKey: 'i_am_lost', category: 'emergency', icon: '📍', translations: { en: 'I am lost', es: 'Estoy perdido/a', fr: 'Je suis perdu(e)', ar: 'أنا تائه', pt: 'Estou perdido/a', ja: '道に迷いました', ko: '길을 잃었습니다', 'zh-CN': '我迷路了', de: 'Ich habe mich verlaufen', it: 'Mi sono perso/a' } },
  { phraseKey: 'lost_child', category: 'emergency', icon: '👶', translations: { en: 'I lost my child', es: 'Perdí a mi hijo/a', fr: "J'ai perdu mon enfant", ar: 'فقدت طفلي', pt: 'Perdi meu filho/a', ja: '子供を見失いました', ko: '아이를 잃어버렸습니다', 'zh-CN': '我的孩子走丢了', de: 'Ich habe mein Kind verloren', it: 'Ho perso il mio bambino/a' } },
  { phraseKey: 'need_translator', category: 'emergency', icon: '🗣️', translations: { en: 'I need a translator', es: 'Necesito un traductor', fr: "J'ai besoin d'un traducteur", ar: 'أحتاج مترجم', pt: 'Preciso de um tradutor', ja: '通訳が必要です', ko: '통역사가 필요합니다', 'zh-CN': '我需要翻译', de: 'Ich brauche einen Dolmetscher', it: 'Ho bisogno di un traduttore' } },
  { phraseKey: 'need_transportation', category: 'emergency', icon: '🚗', translations: { en: 'I need transportation', es: 'Necesito transporte', fr: "J'ai besoin de transport", ar: 'أحتاج وسيلة نقل', pt: 'Preciso de transporte', ja: '交通手段が必要です', ko: '교통수단이 필요합니다', 'zh-CN': '我需要交通工具', de: 'Ich brauche ein Transportmittel', it: 'Ho bisogno di un mezzo di trasporto' } },
  { phraseKey: 'lost_passport', category: 'emergency', icon: '🛂', translations: { en: 'I lost my passport', es: 'Perdí mi pasaporte', fr: "J'ai perdu mon passeport", ar: 'فقدت جواز سفري', pt: 'Perdi meu passaporte', ja: 'パスポートを紛失しました', ko: '여권을 잃어버렸습니다', 'zh-CN': '我的护照丢了', de: 'Ich habe meinen Reisepass verloren', it: 'Ho perso il mio passaporto' } },
  { phraseKey: 'need_medical_assistance', category: 'emergency', icon: '🚑', translations: { en: 'I need medical assistance', es: 'Necesito asistencia médica', fr: "J'ai besoin d'assistance médicale", ar: 'أحتاج مساعدة طبية', pt: 'Preciso de assistência médica', ja: '医療支援が必要です', ko: '의료 도움이 필요합니다', 'zh-CN': '我需要医疗帮助', de: 'Ich brauche medizinische Hilfe', it: 'Ho bisogno di assistenza medica' } },

  // Wayfinding
  { phraseKey: 'where_is_restroom', category: 'wayfinding', icon: '🚻', translations: { en: 'Where is the restroom?', es: '¿Dónde está el baño?', fr: 'Où sont les toilettes ?', ar: 'أين دورة المياه؟', pt: 'Onde fica o banheiro?', ja: 'トイレはどこですか？', ko: '화장실이 어디에 있나요?', 'zh-CN': '洗手间在哪里？', de: 'Wo ist die Toilette?', it: 'Dov\'è il bagno?' } },
  { phraseKey: 'where_is_exit', category: 'wayfinding', icon: '🚪', translations: { en: 'Where is the exit?', es: '¿Dónde está la salida?', fr: 'Où est la sortie ?', ar: 'أين المخرج؟', pt: 'Onde fica a saída?', ja: '出口はどこですか？', ko: '출구가 어디에 있나요?', 'zh-CN': '出口在哪里？', de: 'Wo ist der Ausgang?', it: 'Dov\'è l\'uscita?' } },

  // Hospitality
  { phraseKey: 'where_can_i_eat', category: 'hospitality', icon: '🍽️', translations: { en: 'Where can I eat?', es: '¿Dónde puedo comer?', fr: 'Où puis-je manger ?', ar: 'أين يمكنني الأكل؟', pt: 'Onde posso comer?', ja: 'どこで食事ができますか？', ko: '어디서 밥을 먹을 수 있나요?', 'zh-CN': '哪里可以吃饭？', de: 'Wo kann ich essen?', it: 'Dove posso mangiare?' } },

  // Transport
  { phraseKey: 'how_to_get_to_stadium', category: 'transport', icon: '🏟️', translations: { en: 'How do I get to the stadium?', es: '¿Cómo llego al estadio?', fr: 'Comment aller au stade ?', ar: 'كيف أصل إلى الملعب؟', pt: 'Como chego ao estádio?', ja: 'スタジアムへの行き方は？', ko: '경기장에 어떻게 가나요?', 'zh-CN': '怎么去体育场？', de: 'Wie komme ich zum Stadion?', it: 'Come arrivo allo stadio?' } },
];

console.log(JSON.stringify(phrases, null, 2));
console.log(`\n✅ ${phrases.length} approved phrases generated for review`);
